# Generated by Django 5.0.1 on 2024-01-11 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywdiary', '0002_alter_customuser_username_diaryentry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diaryentry',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='diaryentry',
            name='user',
        ),
    ]
