# Generated by Django 5.0.1 on 2024-01-27 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('mywdiary', '0004_customuser_email_confirmed_alter_customuser_username_and_more'),
    ]

    # operations = [
    #     migrations.AddField(
    #         model_name='diaryentry',
    #         # name='user',
    #         # field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
    #     ),
    # ]

